database-scripts/installation-script/kpi-definitions.js, database-scripts/upgrade-scripts/Release-8.0-from-7.0.js
"threshold" 20%
"maturityRange": ["-50", "50-30", "30-20", "20-10", "10-"]
for scope churn
=> DTS-28878: Change of maturity & threshold for scope churn

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/azureissue/AzureIssueClient.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImpl.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/util/AzureConstants.java
Assignee detail fix when toggle is off for azure.
=> Defect fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ScopeChurnServiceImpl.java
In Scope change of numerator :  issue added + removed with duplicated means if added then removed or vice versa it will be counted again.
File Coverage : 98%
=> DTS-28151:Scope Churn Change Req

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnupServiceImpl.java
Not showing removed issue from release from excel of release burnup
=> DTS-29375:Excel only tag issue to release

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnupServiceImpl.java
Reverts PublicisSapient/PSknowHOW#260
=> Revert "DTS-28151:Release burnup diff prediction filters"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnupServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/CommonUtils.java
Reverts PublicisSapient/PSknowHOW#257
=> Revert "DTS-28608:Removed weekends"

UI/src/app/component/group-bar-chart/group-bar-chart.component.ts
Reverts PublicisSapient/PSknowHOW#256
=> Revert "temp width added"

UI/src/app/component/group-bar-chart/group-bar-chart.component.css, UI/src/app/component/group-bar-chart/group-bar-chart.component.ts, UI/src/app/dashboard/kpi-card/kpi-card.component.html, UI/src/app/dashboard/kpi-card/kpi-card.component.ts, UI/src/app/shared-module/field-mapping-field/field-mapping-field.component.html, UI/src/app/shared-module/field-mapping-field/field-mapping-field.component.ts, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnupServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/IterationKpiValue.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnupServiceImplTest.java, database-scripts/installation-script/kpi-definitions.js, database-scripts/rollback-scripts/Release-8.0-from-7.0-R.js, database-scripts/upgrade-scripts/Release-8.0-from-7.0.js
Reverts PublicisSapient/PSknowHOW#251
=> Revert "Dts 28608 Release burnup Prediction date Logic"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ScopeChurnServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_810/ScopeChurnChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_810/ScopeChurnChangeUnit.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
For Scope Churn kpi, we will have 2 filters Story Points and issue Count, the data will be different for each filter
=> DTS-29120 : Story Points and Issue Count Filter at KPI level

kafka-consumers/notification-consumer/src/main/resources/templates/Error_In_Jira_Processor_Template.html, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/config/JiraProcessorConfig.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/helper/JiraHelper.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerKanban.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerScrum.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/processor/IssueScrumProcessor.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/processor/SprintDataProcessor.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/processor/SprintDataProcessorImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/reader/IssueBoardReader.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/reader/IssueSprintReader.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchEpicDataImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchKanbanReleaseData.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchKanbanReleaseDataImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchScrumReleaseData.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchScrumReleaseDataImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchSprintReport.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchSprintReportImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/JiraCommonService.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/NotificationHandler.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/JiraIssueReleaseStatusTasklet.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/KanbanReleaseDataTasklet.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/MetaDataTasklet.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/ScrumReleaseDataTasklet.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/SprintReportTasklet.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/tasklet/SprintScrumBoardTasklet.java, processors/jira/src/main/resources/application.properties, processors/jira/src/main/resources/templates/Error_In_Jira_Processor_Template.html
Notification format changed, to change that first we needed server name for that I added getApiHost() function then we needed every step to throw exception properly so that in listener we can get that exception msg and lastly a domainName property is added so when we add any domain in properties it only send email to those mails only
=> Dts 29580 jira notification enhancement

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimateVsActualServiceImpl.java
The unit of Estimate Vs Actual was hours, it has been modified to days similar to work remaining kpi
=> Dts 29912 estimate vs actual unit change

UI/src/app/app.module.ts, UI/src/app/dashboard/milestone/milestone.component.html, UI/src/app/dashboard/milestone/milestone.component.ts, UI/src/app/services/feature-toggle.service.ts, UI/src/app/services/http.service.ts
=> Fix for Feature Toggle service not working in Settings, and DTS-30134

processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/helper/AdditionalFilterHelperTest.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/helper/JiraHelperTest.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/helper/ReaderRetryHelperTest.java
=> Jira test coverage

processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/client/JiraClientTest.java
=> JunitTest Class for JiraClientTest

processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/client/JiraClientTest.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/client/JiraOAuthClientTest.java
=> JunitTest Class for Jira

processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/helper/AdditionalFilterHelperTest.java
=> JunitTest Class AdditionalFilterHelper for Jira

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_830/RootCauseFieldMappingChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_830/RootCauseFieldMappingChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/azureissue/AzureIssueClient.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/processor/JiraIssueProcessorImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/processor/KanbanJiraIssueProcessorImpl.java
As a user, I would like to option in the configuration to configure Defect count by RCA through label field, so that KnowHOW can pick the labels defined in Jira for RCA
=> DTS-31070 rca labels mapping

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_830/KpiLinkEnhc.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
Added kpi link 
https://publicissapient.atlassian.net/browse/DTS-31905
didn't added rollback as prev link page will be removed
=> Dts 31905 kpi link update/add

processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java
https://publicissapient.atlassian.net/browse/DTS-31930
=> DTS-31930 RCA defect : 8.3.4

processors/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java
=> DTS-31907 AA client NPE fix

processors/github/src/main/java/com/publicissapient/kpidashboard/gitlab/util/GitHubURIBuilder.java
DTS-31970 github on-prem issue fix on client_master.
=> DTS-31970 github on-prem issue fix on client_master.

processors/azure-repo/src/main/java/com/publicissapient/kpidashboard/azurerepo/constants/AzureRepoConstants.java, processors/azure-repo/src/main/java/com/publicissapient/kpidashboard/azurerepo/processor/AzureRepoProcessorJobExecutor.java, processors/azure-repo/src/main/java/com/publicissapient/kpidashboard/azurerepo/processor/service/impl/AzureRepoServerClient.java
=> DTS-31931 Azure repo changes

UI/src/app/component/groupedstackchart/groupstackchart.component.css, UI/src/app/component/groupedstackchart/groupstackchart.component.html, UI/src/app/component/groupedstackchart/groupstackchart.component.ts, UI/src/app/dashboard/backlog/backlog.component.html, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IterationReadinessServiceImpl.java
For Ticket description refer mention url:- https://publicissapient.atlassian.net/browse/DTS-31751
92.1% is code coverage on sonar server
=> DTS- 31751 Iteration Readiness drill down enhancement

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimationHygieneServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_830/EstimationHygieneEnhnc.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_830/EstimationHygieneEnhnc.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
link to refer description:- https://publicissapient.atlassian.net/browse/DTS-31706
=> DTS- 31706 estimation hygiene KPI Enhc.

customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java
when both the fields custom closed status and issuetype are applied, the intersection is not working correctly, fixed this
=> DTS-31689_Sprint_Tranformation_Fix

UI/src/app/config/project-config/connection-list/connection-list.component.spec.ts, UI/src/app/config/project-config/connection-list/connection-list.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/connection/service/ConnectionServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-29784 - 8.3.5
=> Dts 29784 GitHub action conn

processors/github/src/main/java/com/publicissapient/kpidashboard/github/util/GitHubURIBuilder.java
DTS-31970 github on-prem issue fix.
=> DTS-31970 github on-prem issue fix.

processors/azure-pipeline/src/main/java/com/publicissapient/kpidashboard/azurepipeline/processor/adapter/impl/DefaultAzurePipelineClient.java, processors/azure-pipeline/src/main/java/com/publicissapient/kpidashboard/azurepipeline/util/AzurePipelineUtils.java, processors/azure-pipeline/src/test/java/com/publicissapient/kpidashboard/azurepipeline/util/AzurePipelineUtilsTest.java
DTS-32170 IllegalArgumentException fix
=> DTS-32170 IllegalArgumentException.

processors/azure-pipeline/src/main/java/com/publicissapient/kpidashboard/azurepipeline/processor/AzurePipelineProcessorJobExecutor.java, processors/azure-pipeline/src/main/java/com/publicissapient/kpidashboard/azurepipeline/processor/adapter/impl/DefaultAzurePipelineClient.java
DTS-32170 IllegalArgumentException changes.
=> DTS-32170 IllegalArgumentException changes.

customapi/src/main/resources/application.properties
refer ticket for description: - https://publicissapient.atlassian.net/browse/DTS-32020
=> Fixing invalid connection issue for Test API

customapi/src/main/java/com/publicissapient/kpidashboard/apis/userboardconfig/service/UserBoardConfigServiceImpl.java
Ticket link :-https://publicissapient.atlassian.net/browse/DTS-32255 
In this ticket defect is fixed where user will now be able to customize the knowhow dashboard name.
=> Knowhow dashboard rename Defect fix ## code need to be merged in common master branch

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/FieldMappingStructureForMongock.java
https://publicissapient.atlassian.net/browse/DTS-34674
mongock base field fresh change
=> DTS-34674: ftpr mongock install bug fix

UI/src/app/dashboard/executive/executive.component.ts, UI/src/app/dashboard/trend-indicator/trend-indicator.component.html, UI/src/app/dashboard/trend-indicator/trend-indicator.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/ToolsKPIService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpiintegration/service/KpiIntegrationServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/kanban/service/TeamCapacityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/kanban/service/TicketVelocityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/HappinessIndexServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/kpiintegration/service/KpiIntegrationServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/AutomationPercentageServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageKanbanServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/TestExecutionServiceImplTest.java
[https://publicissapient.atlassian.net/browse/DTS-36109](https://publicissapient.atlassian.net/browse/DTS-36109): Maturity defect fix to show maturity for any number of datapoints selected with info icon on trend box to display the data points number and recommendation API fix
=> DTS-36109 maturity calculation defect

processors/jira-xray-zephyr-squad/src/main/java/com/publicissapient/kpidashboard/jiratest/processor/service/impl/JiraTestServiceImpl.java, processors/jira-xray-zephyr-squad/src/test/java/com/publicissapient/kpidashboard/jiratest/processor/service/impl/JiraTestServiceImplTest.java
In this we have provided a fix for considering test cases having both valid and invalid links.
For more understanding, refer ticketId :- https://publicissapient.atlassian.net/browse/DTS-36062
=> GS Jira Test defect fix- for valid and invalid link

customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/rest/ProcessorController.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpiintegration/rest/KpiIntegrationController.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/service/RepoToolsConfigServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/kpiintegration/rest/KpiIntegrationControllerTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/repotools/service/RepoToolsConfigServiceImplTest.java
[https://publicissapient.atlassian.net/browse/DTS-36381](https://publicissapient.atlassian.net/browse/DTS-36381): encrytion/decryption needed for api keys
=> DTS-36381 Remove API key encryption

UI/src/app/dashboard/backlog/backlog.component.spec.ts, UI/src/app/dashboard/backlog/backlog.component.ts, UI/src/app/dashboard/developer/developer.component.ts, UI/src/app/dashboard/executive/executive.component.ts, UI/src/app/dashboard/trend-indicator/trend-indicator.component.html, UI/src/app/dashboard/trend-indicator/trend-indicator.component.ts
https://publicissapient.atlassian.net/browse/DTS-36109: Defect fix to show msg for cumulative trend
=> DTS-36109 maturity defect

customapi/src/main/java/com/publicissapient/kpidashboard/apis/azure/service/AzureToolConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bamboo/service/BambooToolConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/githubaction/service/GithubActionToolConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/JenkinsToolConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraToolConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarToolConfigServiceImpl.java, processors/argocd/src/main/java/com/publicissapient/kpidashboard/argocd/processor/ArgoCDProcessorJobExecutor.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/adapter/impl/OnlineAdapter.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/adapter/impl/async/ProcessorAsyncAzureRestClientImpl.java, processors/azure-pipeline/src/main/java/com/publicissapient/kpidashboard/azurepipeline/processor/AzurePipelineProcessorJobExecutor.java, processors/azure-repo/src/main/java/com/publicissapient/kpidashboard/azurerepo/processor/AzureRepoProcessorJobExecutor.java, processors/bamboo/src/main/java/com/publicissapient/kpidashboard/bamboo/client/impl/BambooClientBuildImpl.java, processors/bamboo/src/main/java/com/publicissapient/kpidashboard/bamboo/client/impl/BambooClientDeployImpl.java, processors/bitbucket/src/main/java/com/publicissapient/kpidashboard/bitbucket/processor/BitBucketProcessorJobExecutor.java, processors/github-action/src/main/java/com/publicissapient/kpidashboard/githubaction/processor/GitHubActionProcessorJobExecutor.java, processors/github/src/main/java/com/publicissapient/kpidashboard/github/processor/GitHubProcessorJobExecutor.java, processors/gitlab/src/main/java/com/publicissapient/kpidashboard/gitlab/processor/GitLabProcessorJobExecutor.java, processors/jenkins/src/main/java/com/publicissapient/kpidashboard/jenkins/processor/JenkinsProcessorJobExecutor.java, processors/jira-zephyr-scale/src/main/java/com/publicissapient/kpidashboard/zephyr/processor/service/impl/ZephyrCloudImpl.java, processors/jira-zephyr-scale/src/main/java/com/publicissapient/kpidashboard/zephyr/processor/service/impl/ZephyrServerImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/FetchSprintReportImpl.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/JiraCommonService.java, processors/sonar/src/main/java/com/publicissapient/kpidashboard/sonar/processor/SonarProcessorJobExecutor.java, processors/teamcity/src/main/java/com/publicissapient/kpidashboard/teamcity/processor/TeamcityProcessorJobExecutor.java
Maintained Http reason phrase against status code as error message.
=> DTS 35358 defect fixed for broken connection

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/rest/KPIExcelDataController.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/rest/KPIExcelDataControllerTest.java
https://publicissapient.atlassian.net/browse/DTS-36506: fix for the kpi excel bug caused by removing api key encryption
=> DTS-36506 excel bug

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/ToolsKPIService.java, customapi/src/main/resources/application.properties
https://publicissapient.atlassian.net/browse/DTS-36137 rename debbie to scm-processor
https://publicissapient.atlassian.net/browse/DTS-36109: dev tab bug fix
=> Dts 36109 maturity defect

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/ToolsKPIService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/connection/service/TestConnectionServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrService.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/kanban/service/TeamCapacityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/kanban/service/TicketVelocityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/AutomationPercentageServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/TestExecutionServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-36627: regression issue caused due to maturity defect fix
=> DTS-36627 kanban fix

UI/src/app/config/profile/myprofile/myprofile.component.css, UI/src/app/config/profile/myprofile/myprofile.component.html, UI/src/app/config/profile/myprofile/myprofile.component.spec.ts, UI/src/app/config/profile/myprofile/myprofile.component.ts, UI/src/app/services/http.service.ts, common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UserDetailsResponseDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UserInfo.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UserInfoDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/service/NotificationService.java, common/src/main/java/com/publicissapient/kpidashboard/common/service/NotificationServiceImpl.java, common/src/test/java/com/publicissapient/kpidashboard/common/service/NotificationServiceImplTest.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/abac/ProjectAccessManager.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/service/ForgotPasswordServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/UserInfoService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/CommonServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/CustomAnalyticsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserInfoServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/rbac/userinfo/rest/UserInfoController.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/UserInfoServiceImplTest.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/NotificationHandler.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/service/NotificationHandlerTest.java
Access Alert - access management email
Error Alert - Jira failure email 
https://publicissapient.atlassian.net/browse/DTS-36474
=>  DTS-36474 - Notification Alert Email flag User wise 

central-auth-service/central-login-ui-react/src/components/PSLogo/index.jsx, central-auth-service/central-login-ui-react/src/components/SuiteLogos/index.jsx, central-auth-service/central-login-ui-react/src/pages/login/index.jsx, central-auth-service/central-login-ui-react/src/pages/register/index.jsx
The user can log in while the user name contains a special character like "@"
=> DTS-36150: The user can log in while the user name contains a special character like "@"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrService.java
https://publicissapient.atlassian.net/browse/DTS-36669: Sprint and squad filter defect fix
=> DTS-36669 sprint squad fix

UI/src/app/config/profile/myprofile/myprofile.component.html, UI/src/app/config/profile/myprofile/myprofile.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/abac/ProjectAccessManager.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/CommonServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserInfoServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/rbac/userinfo/rest/UserInfoController.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerKanban.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerScrum.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/NotificationHandler.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/service/NotificationHandlerTest.java
Notification Preferences *applies to PROJECT_ADMIN and SUPERADMIN roles only and
Make SUPERADMIN role eligible to receive Error alerts for Jira
https://publicissapient.atlassian.net/browse/DTS-36708
https://publicissapient.atlassian.net/browse/DTS-36709
=> DTS-36708, DTS-36709 notification defects fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java
Added Capacity is not updated on Team Capacity on Kanban Projects
=> Added Capacity is not updated on Team Capacity on Kanban Projects

UI/src/app/config/project-config/connection-list/connection-list.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRSizeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PickupTimeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RepoToolMeanTimeToMergeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/connection/service/TestConnectionServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_920/AzureRepoToolProvider.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_920/AzureRepoToolProvider.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolConfig.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/service/RepoToolsConfigServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-30436: Enable Azure Repository for RepoTool
https://publicissapient.atlassian.net/browse/DTS-36695: Developer dashboard defect fixes
=> DTS-66695 dev kpis defects

common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CommittmentReliabilityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
https://publicissapient.atlassian.net/browse/DTS-27532
=> Dts 27532 commitement KPI - scope Field

UI/src/app/config/advanced-settings/advanced-settings.component.css, UI/src/app/config/advanced-settings/advanced-settings.component.html, UI/src/app/config/advanced-settings/advanced-settings.component.ts
https://publicissapient.atlassian.net/browse/DTS-36853
=> scroll and delete button issue fixed

.github/workflows/Github_CI_Master.yaml, UI/src/app/dashboard/milestone/milestone.component.html, central-auth-service/docker-compose.yaml, docker-compose.yaml
Reverts PublicisSapient/PSknowHOW#991
=> Revert "Hotfix 9.1.0"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrService.java
https://publicissapient.atlassian.net/browse/DTS-36918: changes in JiraServiceR and ZephyrService common code for Jira kpis in speed/quality/value
=> DTS-36918: <5 sprints fix

UI/src/app/config/profile/view-new-user-auth-request/view-new-user-auth-request.component.css, UI/src/app/config/profile/view-new-user-auth-request/view-new-user-auth-request.component.html, UI/src/app/config/profile/view-new-user-auth-request/view-new-user-auth-request.component.spec.ts, UI/src/app/model/userAccessApprovalDTO.model.ts, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/CentralUserInfoDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UserAccessApprovalResponseDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/AuthProperties.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/service/AuthenticationService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/service/DefaultAuthenticationServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/UserInfoService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserInfoServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/rbac/accessrequests/service/AccessRequestsHelperServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/rbac/signupapproval/rest/SignupRequestsController.java, customapi/src/main/resources/application.properties, customapi/src/test/java/com/publicissapient/kpidashboard/apis/auth/service/AuthenticationServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/rbac/signupapproval/rest/SignupRequestsControllerTest.java
https://publicissapient.atlassian.net/browse/DTS-31549 
while SUPERADMIN approving user email not belonging to the whitelisted domain so that I see a warning while approving.
Highlight in UI and showing warning msg on hover
=> Dts 31549 user access - Not whiltelist email highlighted

processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/constant/JiraConstants.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/helper/AdditionalFilterHelper.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/helper/AdditionalFilterHelperTest.java
https://publicissapient.atlassian.net/browse/DTS-36961
adjusted the code to work for tapestry client as well for their squad configured as the jira response provide "name" and no "value"
=> Dts 36961 additional filter defect

processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerKanban.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/listener/JobListenerScrum.java
=> Board Trace Log Fix

UI/src/app/dashboard/milestone/milestone.component.html, UI/src/app/dashboard/milestone/milestone.component.spec.ts, UI/src/app/dashboard/milestone/milestone.component.ts
Reverts PublicisSapient/PSknowHOW#1002
=> Revert "milestone unit test  removed"

processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/scheduler/JobScheduler.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/OngoingExecutionsService.java
Making the execution ongoing flag true when the ExecutorService launch the job , 
Earlier it was set to true once jobParam is being build causing mannual trigger to stop until cron is completed
=> Dts 34923 : Flagging executionOngoing Flag to true when Executor launch the job

UI/src/app/component/export-excel/export-excel.component.css, UI/src/app/component/export-excel/export-excel.component.html, UI/src/app/component/export-excel/export-excel.component.ts, UI/src/app/dashboard/iteration/iteration.component.css
https://publicissapient.atlassian.net/browse/DTS-36996
https://publicissapient.atlassian.net/browse/DTS-37059
1. Hide filters coumn which have object json
2. fixed download excel issue
=> DTS-36995 & DTS-3759 explore table filter issues

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bamboo/service/BambooToolConfigServiceImpl.java
This pull request contains only one change, as mentioned in the attached file. Since there is no corresponding JIRA ticket for this, I am referring to it with the existing scan fixes branch.
[Server-side request forgery · Code scanning alert #891 · marriott_PSknowHOW.pdf](https://github.com/PublicisSapient/PSknowHOW/files/15456486/Server-side.request.forgery.Code.scanning.alert.891.marriott_PSknowHOW.pdf)
=> Merging Marriott CODE QL scan fixes to develop

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_920/UpdateMeanTimeToRecover.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_920/UpdateMeanTimeToRecover.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
DTS-36197:Improvements on KH widgets for EJ Project
=> DTS-36197:Improvements on KH widgets for EJ Project

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_920/UpdateMeanTimeToRecover.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_920/UpdateMeanTimeToRecover.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
PublicisSapient/PSknowHOW#1025
=> "DTS-36197:Improvements on KH widgets for EJ Project""

UI/src/app/config/advanced-settings/advanced-settings.component.spec.ts, UI/src/app/config/advanced-settings/advanced-settings.component.ts
Hiding jira progress-bar when processor run fails on server
=> Dts 37034 progressbar loading

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java
This is for testing the git process.
=> feature 1 change

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java
changes for testing the git process.
=> feature 2 change

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java
Reverts PublicisSapient/PSknowHOW#1032
=> Revert "feature 2 change"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrService.java
https://publicissapient.atlassian.net/browse/DTS-36918: hotfix for master
=> DTS-36918: hotfix

UI/src/app/shared-module/conditional-input/conditional-input.component.ts
My Knowhow/Quality → First Time Pass Rate
Iteration -->First Time Pass Rate
Selected priority values are getting saved and data is filtering on graph, but those values are not showing on ui
=> DTS-37117: FTPR_SelectedPriority_DataLoad

UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/nav-v2/nav-new.component.html
prefix the selections with the filter type
Remove Pencil icon on MyKnowHOW
=> DTS-35435_prefix the selections with the filter type

UI/src/app/shared-module/conditional-input/conditional-input.component.spec.ts
=> DTS-37117_somarissues-fixes

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_930/UpdateBuildFrequency.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_930/UpdateBuildFrequency.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
https://publicissapient.atlassian.net/browse/DTS-36658: updated build frequency maturity
=> DTS-36658: build frequency maturity

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DevCompletionStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimateVsActualServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-37358
=> DTS-37358_squad filters not working for 2 kpis

UI/src/app/shared-module/conditional-input/conditional-input.component.html, UI/src/app/shared-module/conditional-input/conditional-input.component.ts
=> DTS-37117_PriorityFilter-FTPR

customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiHelperServiceTest.java
Reverts PublicisSapient/PSknowHOW#1054
=> Revert "Dts 30141 sprint capacity kpi"

common/src/main/java/com/publicissapient/kpidashboard/common/util/DateUtil.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleasePlanServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseKPIService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseServiceR.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnUpServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleasePlanServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseKPIServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseServiceRTest.java
https://publicissapient.atlassian.net/browse/DTS-32206
https://publicissapient.atlassian.net/browse/DTS-37451
=> Hotfix release plan

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleasePlanServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-37451
=> Defect fix release plan

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/QualityStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/IterationKpiModalValue.java
Add dummy value to the linkeddefect column of unlinked defect modal
=> GS QualityStatusServiceImpl.java

UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/header-v2/header.component.ts, UI/src/app/dashboardv2/nav-v2/nav-new.component.ts
DTS-37349_BackToDashboard
Kanban/Scrum selection hold from back to dashboard
modified back to dashboard functionality
=> DTS-37349_BackToDashboard

UI/src/app/app.module.ts, UI/src/app/component/comments-v2/comments-v2.component.css, UI/src/app/component/comments-v2/comments-v2.component.html, UI/src/app/component/comments-v2/comments-v2.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.css, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
Open comments dialog in new UI for individual KPI
=> DTS-37349 Comments Dialog

common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepository.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryCustom.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/JiraFeature.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/LoggedTimePerIssue.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiHelperServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImplTest.java
Reverts PublicisSapient/PSknowHOW#1078
https://publicissapient.atlassian.net/browse/DTS-37490
=> Revert "Revert "review comment fix""

common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepository.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryCustom.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/JiraFeature.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/releasedashboard/JiraReleaseServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/LoggedTimePerIssue.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiHelperServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintCapacityServiceImplTest.java
Reverts PublicisSapient/PSknowHOW#1130
https://publicissapient.atlassian.net/browse/DTS-37490
=> Revert "Revert "Revert "Revert "review comment fix""""

UI/src/app/dashboardv2/filter-v2/filter-new.component.css, UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
Add Duration, Remaining days for iteration dashboard
=> DTS-38257_Add Duration, Remaining days

UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
Hiding capacity and if no sprint then hide the entire container
=> DTS-38257_Duration-RemainingDays

UI/src/app/config/advanced-settings/advanced-settings.component.ts, UI/src/app/config/project-config/jira-config/jira-config.component.ts, UI/src/app/dashboard/issue-body/issue-body.component.ts, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/trend-indicator-v2/trend-indicator-v2.component.ts, UI/src/app/page-not-found/page-not-found.component.ts, UI/src/app/shared-module/conditional-input/conditional-input.component.ts, UI/src/app/shared-module/field-mapping-field/field-mapping-field.component.ts, UI/src/app/shared-module/kpi-filter/kpi-filter.component.ts
Handled non logical critical issues only
=> DTS-38282_Critical-Issues

UI/src/app/config/advanced-settings/advanced-settings.component.ts, UI/src/app/config/profile/profile.component.css, UI/src/app/config/profile/view-requests/view-requests.component.html, UI/src/app/config/project-config/basic-config/basic-config.component.html, UI/src/app/config/project-config/field-mapping/field-mapping.component.ts, UI/src/app/config/upload/upload.component.ts, UI/src/app/dashboard/daily-scrum/daily-scrum.component.html, UI/src/app/dashboard/developer/developer.component.ts, UI/src/app/dashboard/dora/dora.component.ts, UI/src/app/dashboard/executive/executive.component.ts, UI/src/app/dashboard/filter/filter.component.ts, UI/src/app/dashboard/kpi-card/kpi-card.component.ts, UI/src/app/dashboard/trend-indicator/trend-indicator.component.html, UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts, UI/src/app/dashboardv2/header-v2/header.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.css, UI/src/app/feedback/feedback.component.css, UI/src/app/services/sso.guard.ts, UI/src/app/shared-module/footer/footer.component.html, UI/src/app/shared-module/project-filter/project-filter.component.html, UI/src/styles.css
handling major and critical issues count
=> DTS 38282 code quality check

UI/src/app/config/project-config/jira-config/jira-config.component.ts, UI/src/app/dashboard/backlog/backlog.component.ts, UI/src/app/dashboard/executive/executive.component.ts
handling critical issues count
=> DTS-38384 DTS-38282

UI/src/app/config/advanced-settings/advanced-settings.component.css, UI/src/app/config/advanced-settings/advanced-settings.component.html, UI/src/app/config/advanced-settings/advanced-settings.component.ts, common/src/main/java/com/publicissapient/kpidashboard/common/model/ProcessorExecutionTraceLog.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolsStatusResponse.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/service/RepoToolsConfigServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/appsetting/service/ProcessorServiceImplTest.java
Reverts PublicisSapient/PSknowHOW#1129 https://publicissapient.atlassian.net/browse/DTS-37072 as it is removed from release
=> Revert "Dts 37072 api hit limit"

UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts
=> DTS-38384_CriticalOnly

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts
reducing complexity for executive-v2.component file
=> DTS-38384_Critical-executive-v2

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts
=> DTS-38384_ExecutiveV2

UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.css, UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.css, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.css
added capitalize text transform for label name
=> case correction for filter label name DTS-35428

UI/src/app/component/tooltip-v2/tooltip-v2.component.css, UI/src/app/component/tooltip/tooltip.component.css, UI/src/app/dashboard/kpi-card/kpi-card.component.css, UI/src/app/dashboard/kpi-card/kpi-card.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts
https://publicissapient.atlassian.net/browse/DTS-38624
https://publicissapient.atlassian.net/browse/DTS-38697
https://publicissapient.atlassian.net/browse/DTS-38660
=> consolidated new UI bugs

UI/src/app/config/dashboard-config/dashboard-config.component.spec.ts, UI/src/app/dashboard/backlog/backlog.component.spec.ts, UI/src/app/dashboard/backlog/backlog.component.ts, UI/src/app/dashboard/kpi-card/kpi-card.component.spec.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.spec.ts
=> Dts 38760 UI coverge

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/CodeCommitServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java
10.0.0 bugfix https://publicissapient.atlassian.net/browse/DTS-38915
=> DTS-38915: commit kpi excel defect fix

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimateVsActualServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimationHygieneServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1010/HygieneEstimateLogic.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1010/HygieneEstimateLogic.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, customapi/src/test/resources/json/default/scrum_project_field_mappings.json
https://publicissapient.atlassian.net/browse/DTS-38041
=> DTS-38041 | estimate hygiene logic sync | <Release 10.1.0>

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DREServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/QualityStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1010/UpdateDreDdQsFieldMapping.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1010/UpdateDreDdQsFieldMapping.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DREServiceImplTest.java, customapi/src/test/resources/json/default/jira_issue_custom_history.json, customapi/src/test/resources/json/default/scrum_project_field_mappings.json, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java, processors/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImplTest.java, processors/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java, processors/jira/src/test/resources/json/default/metadata_identifier.json
https://publicissapient.atlassian.net/browse/DTS-38030
=> Dts 38030 dir/dd/dre fm

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1010/UpdateEstimationNestedField.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1010/UpdateEstimationNestedField.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
the nested field of conversion is to be present in the estimation criteria field in global mapping to be present on both the radio buttons.
https://publicissapient.atlassian.net/browse/DTS-38565
=> DTS-38565_EstimationCriteria_NestedField (10.1.0)

processors/azure-repo/src/main/java/com/publicissapient/kpidashboard/azurerepo/processor/service/impl/AzureRepoServerClient.java, processors/bitbucket/src/main/java/com/publicissapient/kpidashboard/bitbucket/processor/service/impl/BitBucketServerClient.java, processors/github/src/main/java/com/publicissapient/kpidashboard/github/constants/GitHubConstants.java, processors/github/src/main/java/com/publicissapient/kpidashboard/github/processor/service/impl/GitHubClientImpl.java, processors/gitlab/src/main/java/com/publicissapient/kpidashboard/gitlab/constants/GitLabConstants.java, processors/gitlab/src/main/java/com/publicissapient/kpidashboard/gitlab/processor/service/impl/GitLabClient.java
DTS-38951:Update Mean Time To Merge Logic to Include Merge Data in Duration Calculation
=> DTS-38951:Update Mean Time To Merge Logic to Include Merge Data in Duration Calculation

UI/src/app/config/config.component.ts
https://publicissapient.atlassian.net/browse/DTS-37687
=> DTS 37687 cosmetic change

UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.html, UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.html, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
=> Multiselect Fix: moving selected option to top in all multiselect dropdowns

UI/src/app/config/project-config/jira-config/jira-config.component.ts
DTS-39126:While configuring the invalid Jenkins connection. unable to see the pop-up message
=> DTS-39126:While configuring the invalid Jenkins connection. unable to see the pop up message

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/QualityStatusServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-39221
=> Quality status defect fix

UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html
should display a message on the KPIs (whether data is available or not) to inform the user which KPIs can be filtered according to the sprint selection
=> DTS-38653 Fix for KPI data/no data message

common/src/main/java/com/publicissapient/kpidashboard/common/feature/FeatureEnum.java
=> By Default enabling New Ui

common/src/test/java/com/publicissapient/kpidashboard/common/feature/FeatureEnumTest.java
=> test case failure fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DCServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/RCAServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, customapi/src/test/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtilityTest.java
Ticket link: - https://publicissapient.atlassian.net/browse/DTS-38032
=> DTS 38032 DSR and DCP Enhancement

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts
Tab order fix(https://publicissapient.atlassian.net/browse/DTS-38555)
=> Tab Order fix

UI/src/app/app.component.ts, UI/src/app/app.module.ts, UI/src/app/dashboardv2/dashboard-v2/dashboard-v2.component.css, UI/src/app/dashboardv2/dashboard-v2/dashboard-v2.component.html, UI/src/app/dashboardv2/dashboard-v2/dashboard-v2.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/sticky-header-v2/sticky-header-v2.component.css, UI/src/app/dashboardv2/sticky-header-v2/sticky-header-v2.component.html, UI/src/app/dashboardv2/sticky-header-v2/sticky-header-v2.component.spec.ts, UI/src/app/dashboardv2/sticky-header-v2/sticky-header-v2.component.ts
New feedback Changes(https://publicissapient.atlassian.net/browse/DTS-39290)
=> Dts 39290 new UI feedback

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DevCompletionStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkRemainingServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-39590
=> DTS-39590: date format fix GS

common/src/main/java/com/publicissapient/kpidashboard/common/config/WebMVCConfig.java, customapi/pom.xml, customapi/src/main/java/com/publicissapient/kpidashboard/apis/CustomApiApplication.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/config/OpenApiConfig.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/config/WebSecurityConfig.java, customapi/src/main/resources/application.properties, customapi/src/test/java/com/publicissapient/kpidashboard/apis/config/CustomWebMVCConfig.java
https://publicissapient.atlassian.net/browse/DTS-39094
=> customapi swagger impl code | Release 10.2.0

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/DefectRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/InnovationRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/config/CustomApiConfig.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPICode.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1020/DefectRateKpi.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1020/InnovationRateKpi.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1020/DefectRateKpi.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1020/InnovationRateKpi.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/Branches.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolKpiMetricResponse.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolRepositories.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolUserDetails.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolValidationData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/resources/application.properties, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, customapi/src/main/resources/json/mongock/default/kpi_master.json, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/DefectRateServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/InnovationRateServiceImplTest.java, customapi/src/test/resources/json/non-JiraProcessors/repo_tools_response.json
https://publicissapient.atlassian.net/browse/DTS-39032
https://publicissapient.atlassian.net/browse/DTS-28729
=> DTS-28729 & DTS-39032

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CommittmentReliabilityServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-40339
=> DTS-40339_Commitment_Reliability_Ambiguity_fix

UI/sonar-project.properties
Reverts PublicisSapient/PSknowHOW#1525
=> Revert "sonar issue fix"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/kanban/service/ProjectVersionKanbanServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ProjectVersionServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-40356
=> DTS-40356: Filter to include only released versions

common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/jira/MetadataValue.java, common/src/main/java/com/publicissapient/kpidashboard/common/service/BoardMetadataService.java, common/src/main/java/com/publicissapient/kpidashboard/common/service/BoardMetadataServiceImpl.java, common/src/test/java/com/publicissapient/kpidashboard/common/service/BoardMetadataServiceImplTest.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/service/ConfigHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/service/EditKpiConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/CacheService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/CacheServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/ApplicationStartupListener.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/fieldmapping/service/FieldMappingServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/CommonUtils.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/appsetting/service/ConfigHelperServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/appsetting/service/EditKpiConfigServiceImplTest.java, processors/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/processor/mode/impl/online/AzureOnlineRunnable.java, processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java
https://publicissapient.atlassian.net/browse/DTS-39547
=> Dts 39547 duplicate issuetype fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
https://publicissapient.atlassian.net/browse/DTS-39590
=> DTS-39590: release freq & COD date fix

UI/src/app/dashboardv2/executive-v2/executive-v2.component.html, UI/src/app/dashboardv2/executive-v2/executive-v2.component.spec.ts, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.spec.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
Change log:
1. Fixes for PI Predictability and Sonar Code Quality KPIs
2. Pull of develop
3. Test cases
=> DTS-29712: Bug fixes for zero data

UI/src/app/dashboard/maturity/maturity.component.ts, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html, UI/src/app/services/shared.service.ts
Change Log:
1. Not hiding Overall for SingleSelect dropdowns
2. Conditions for hiding KPI Filters and Trend Indicator whenever "KPI Cannot Be Measured for a Squad" message is displayed
3. Removing Squad filter functionality
4. Prod Issue fix for "KPI Cannot be measured for Squad" on Value
5. DTS-38552
6. Spinner on Blocked UI
7. Hiding Dora tab on KPI Maturity
=> DTS-40986 + P2 issue

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BackLogCountByStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1020/BacklogCountByStatusAndIterationReadiness.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1020/BacklogCountByStatusAndIterationReadiness.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
1.) Changed one Backlog count by status field to multiInput
2.) Updated Itr readiness field label name.
3.) Backward compatibility script
=> DTS-39650 : Cosmetic changes

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.spec.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
**Change Log:**
1. DTS-40926
2. DTS-41021
3. Test cases
=> DTS-40926, DTS-41021

processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/service/CreateMetadataImpl.java
missed processor change fix i.e. updating one jira field from String to List
=> DTS 39650 DTCC backlog&itr

UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.html, UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1020/RemoveAdditionalFiltersChangeUnit.java, customapi/src/main/resources/json/mongock/default/filters.json
Change-log: Value dashboard doesn't require additional filter
<No ticket for it>
=> remove_value_additional_filters

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/DefectRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRDeclineRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRSuccessRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RevertRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolValidationData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
https://publicissapient.atlassian.net/browse/DTS-39041
https://publicissapient.atlassian.net/browse/DTS-39039
https://publicissapient.atlassian.net/browse/DTS-39043
added additional columns in explore for above kpis
=> DTS_39041, DTS-39043, DTS-39039 developer kpis fixes

UI/src/app/services/helper.service.ts, central-auth-service/authapi/src/main/java/com/publicissapient/kpidashboard/apis/service/impl/NotificationServiceImpl.java, central-auth-service/authapi/src/main/resources/application.properties
authnauth Logout Issue
Mail issue fix
=> authnauth logout issue : removed extra api call which was happening in java8

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/additional-filter/additional-filter.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.spec.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
Changelog: 
Fixes for DTS-41118, DTS-41117, DTS-40296
Test cases
=> DTS-41118, DTS-41117, DTS-40296

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByPriorityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByRCAServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DefectCountByStatusServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FTPRServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/QualityStatusServiceImpl.java, customapi/src/test/resources/json/default/scrum_project_field_mappings.json
Change-log: Cache value modified due to pass by ref, Bug Fix
=> DTS-39547: Quality Kpi bug fix

common/src/main/java/com/publicissapient/kpidashboard/common/service/AssigneeDetailsService.java, common/src/main/java/com/publicissapient/kpidashboard/common/service/AssigneeDetailsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRDeclineRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRSuccessRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RevertRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRDeclineRateServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PRSuccessRateServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RevertRateServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-41169
https://publicissapient.atlassian.net/browse/DTS-41168
=> DTS-41169: user email mapping

UI/src/app/dashboard/filter/filter.component.ts, UI/src/app/dashboard/iteration/iteration.component.ts, UI/src/app/dashboard/nav/nav.component.spec.ts, UI/src/app/dashboard/nav/nav.component.ts
All 3 files changes are for Old UI, so no impact on New UI.
Verified on both Open Source and PS Instance.
=> Old UI Navigation P0 fix

UI/src/app/dashboardv2/executive-v2/executive-v2.component.html, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IterationReadinessServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseBurnUpServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleasePlanServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/IterationKpiValue.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/service/RepoToolsConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
Reverts PublicisSapient/PSknowHOW#1636
=> Revert "Fixathon - Y-Axis label update"

UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts
Reverts PublicisSapient/PSknowHOW#1644
Reverting changes which did to fix the multi-select filter blocker issue because of filter retention code
=> Revert "multi-select blocker issue fixed" #1644

UI/src/app/component/multiline-style-v2/multiline-style-v2.component.ts, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.spec.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts, UI/src/app/services/shared.service.ts
Reverts PublicisSapient/PSknowHOW#1627
Reverting filter retention code since it was impacting basic KPI level filter functionality
@prabasak23 @ananthpal
=> Revert "Dts 40123 retain kpi filter across dashboards" #1627

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RepoToolCodeCommitServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-41270
=> DTS-41270: code commit explore fix

UI/src/app/component/export-excel/export-excel.component.html, UI/src/app/dashboard/iteration/iteration.component.html
Date formate is restored to 'yyyy-MM-dd' for iteration and export excel component.
=> fixathon: Date formate fix

UI/src/app/config/project-config/config-settings/config-settings.component.spec.ts, UI/src/app/config/project-config/tool-menu/tool-menu.component.spec.ts, UI/src/app/config/upload/upload.component.spec.ts, UI/src/app/config/upload/upload.component.ts
Note: removed selectFilterType in upload.component.ts file as the function is not utilized anywhere in the application
=> DTS-41323: improving code coverage

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrServiceKanban.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiHelperServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrServiceKanbanTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/ZephyrServiceTest.java
https://publicissapient.atlassian.net/browse/DTS-41663
=> DTS-41663:Testing Kpis error message handle

common/src/main/java/com/publicissapient/kpidashboard/common/util/DateUtil.java, processors/argocd/src/main/java/com/publicissapient/kpidashboard/argocd/ArgoCDProcessorApplication.java, processors/argocd/src/main/java/com/publicissapient/kpidashboard/argocd/client/ArgoCDClient.java, processors/argocd/src/test/java/com/publicissapient/kpidashboard/argocd/client/ArgoCDClientTest.java
Changelog:Formating the changes with PSKnowHOW formatter,
=> DTS-41542_Adding ARGOCDCoverage

UI/sonar-project.properties, UI/src/app/dashboardv2/executive-v2/executive-v2.component.html, UI/src/app/dashboardv2/executive-v2/executive-v2.component.spec.ts, UI/src/app/dashboardv2/executive-v2/executive-v2.component.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.spec.ts, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.html
Reverts PublicisSapient/PSknowHOW#1664
=> Revert "DTS-41133"

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CostOfDelayServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1110/CODKpiFieldMapping.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1110/CODKpiFieldMapping.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CostOfDelayServiceImplTest.java, customapi/src/test/resources/json/default/scrum_project_field_mappings.json
https://publicissapient.atlassian.net/browse/DTS-41616
=> feature/DTS-41616: codKpiFieldMapping-fix-KK

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/PickupTimeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RepoToolMeanTimeToMergeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/MergeRequests.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolValidationData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
https://publicissapient.atlassian.net/browse/DTS-41234
=> fix/DTS-41234 pickupTimeKPI-fix-kk

UI/src/app/component/export-excel/export-excel.component.ts, UI/src/app/dashboard/iteration/iteration.component.ts, UI/src/app/services/helper.service.ts, UI/src/app/shared-module/pipes/iso-date-format.pipe.spec.ts, UI/src/app/shared-module/pipes/iso-date-format.pipe.ts
added function to manage table header for date
=> DTS-41709: updated code logic to handle different date format

common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryCustom.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/KPIExcelColumn.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CreatedVsResolvedServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DCServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DREServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DRRServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DSRServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/RCAServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/BacklogEpicProgressServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CommitmentReliabilityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CreatedVsResolvedServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DCServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DIRServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DREServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DRRServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DSRServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintVelocityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/release/ReleaseEpicProgressServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtilityTest.java, customapi/src/test/resources/json/default/jira_issues.json
https://publicissapient.atlassian.net/browse/DTS-41791
=> Bug fix/dts 41791 additional field column defect fix

common/src/main/java/com/publicissapient/kpidashboard/common/repository/jira/JiraIssueRepositoryImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DIRServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/FirstTimePassRateServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/QADDServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtilityTest.java
In Quality KPI appended project name is not coming with Sprint Name in sprint name column
Change log:
Sprint Name fix
API build only
=> DTS-41903: Quality KPI Regression Issue

UI/src/app/config/project-config/tool-menu/tool-menu.component.ts
Change log:
Bitbucket Connection Name Defect
UI Build only
=> DTS 41676 UI Defect connection name

UI/src/app/config/advanced-settings/advanced-settings.component.css, UI/src/app/config/advanced-settings/advanced-settings.component.html, UI/src/app/dashboard/filter/filter.component.ts, UI/src/app/dashboard/nav/nav.component.ts, UI/src/test/resource/fakeGlobalConfigData.json, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/UserBoardConfigEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1120/DashboardLabelUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1120/DashboardLabelUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/userboardconfig/service/UserBoardConfigServiceImpl.java, customapi/src/main/resources/json/mongock/default/kpi_master.json, customapi/src/test/java/com/publicissapient/kpidashboard/apis/userboardconfig/service/UserBoardConfigServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-41928
=> DTS-41928: updated dashboard labels

customapi/src/main/resources/application.properties
updated application properties of kpis for kpi graph to show 6 data points instead of 5
=> Kpi datapoint properties changes to 6

UI/src/app/services/http.service.ts, common/src/main/java/com/publicissapient/kpidashboard/common/constant/AuthenticationEvent.java, common/src/main/java/com/publicissapient/kpidashboard/common/constant/Status.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UsersLoginHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/rbac/UsersSession.java, common/src/main/java/com/publicissapient/kpidashboard/common/repository/rbac/UsersSessionRepository.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/CustomAuthenticationFailureHandler.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/rest/UserTokenDeletionControllerApplication.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/auth/token/TokenAuthenticationServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/UserLoginHistoryService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/UsersSessionService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/CustomAnalyticsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserInfoServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserLoginHistoryServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UsersSessionServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/config/CustomApiConfig.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/installation/CreateDatabaseIndexesChangeLog.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1200/UsersSessionChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1200/UsersSessionChangeUnit.java, customapi/src/main/resources/application.properties, customapi/src/test/java/com/publicissapient/kpidashboard/apis/auth/rest/UserTokenDeletionControllerApplicationTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/auth/token/TokenAuthenticationServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/CustomAnalyticsServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserLoginHistoryServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/impl/UsersSessionServiceImplTest.java
Change-log: Invalidate token on user logout.
https://publicissapient.atlassian.net/browse/DTS-41517
=> DTS-41517: Invalidate token after logout

UI/src/app/config/project-config/basic-config/basic-config.component.css, UI/src/app/config/project-config/basic-config/basic-config.component.html, UI/src/app/config/project-config/basic-config/basic-config.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java
https://publicissapient.atlassian.net/browse/DTS-42145
=> DTS-42145: skip scm tool config while cloning

UI/src/app/services/helper.service.ts
=> Bug fix/DTS 42549 UI kanban explore defect

UI/src/app/config/project-config/basic-config/basic-config.component.ts, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
https://publicissapient.atlassian.net/browse/DTS-42115
https://publicissapient.atlassian.net/browse/DTS-43151
=> DTS-43152: renamed project save button and skip mapping history 

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1210/KpiColumnConfigUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1210/KpiColumnConfigUpdate.java, customapi/src/main/resources/json/mongock/default/project_kpi_column_config.json
https://publicissapient.atlassian.net/browse/DTS-43082
=> DTS-43082: kanban cost of delay explore defect

UI/src/app/shared-module/field-mapping-form/field-mapping-form.component.html
https://publicissapient.atlassian.net/browse/DTS-43153
=> DTS-43153: field mapping alignment fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1210/IncludeKPIInDashBoardKPI.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1210/IncludeKPIInDashBoardKPI.java, customapi/src/main/resources/json/mongock/default/kpi_category_mapping.json
=> DTS 40347 include left Out KPI

UI/src/app/config/project-config/project-list/project-list.component.css, UI/src/app/config/project-config/project-list/project-list.component.html, UI/src/app/config/project-config/project-list/project-list.component.ts, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/ProjectBasicConfigServiceImplTest.java
=> DTS-41573: Rename Project

UI/src/app/dashboardv2/filter-v2/filter-new.component.html, UI/src/app/dashboardv2/filter-v2/filter-new.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/assets/img/Check-white.svg
1. Issue on Hierarchy selection (BU/Vertical/Account/Engagement
2. Alignment issue - Share Icon
=> P0, P3 issues handled

customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1210/KanbanFieldMapping.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1210/KanbanFieldMapping.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
https://publicissapient.atlassian.net/browse/DTS-43574
=> DTS-43574 | Change request for kanban fieldmapping tooltip

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/ProjectBasicConfigServiceImplTest.java
Change-log: Semaphore projects filter with as least one tool configured.
=> DTS-42942: Filter projects with at least one tool config | Semaphore 

UI/src/app/config/dashboard-config/dashboard-config.component.ts
Change log: Remove All From Dash Board Config
=> DTS-43679: Remove All from Dashboard Config

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DailyStandupServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkRemainingServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/IssueKpiModalValue.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1300/SprintVelocityMaturityUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1300/UpdateKpiColumnConfigJobName.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1300/UpdateKpiColumnConfigKpi118Kpi183.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1300/UpdateKpiMasterGroupIdsR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1300/SprintVelocityMaturityUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1300/UpdateKpiColumnConfigJobName.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1300/UpdateKpiColumnConfigKpi118Kpi183.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1300/UpdateKpiMasterGroupIds.java
=> updated version from 12.2.0 to 13.0.0

customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/rest/ProcessorController.java
Change log: jira tool configuration fix
=> DTS-43872: QA_JiraDefectFix_12.2

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiDataCacheServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/fieldmapping/service/FieldMappingServiceImpl.java
Change log: Error Code 500 fix happening due to cache changes
=> DTS-43919: QA_DefectFix_12.2

customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/KpiDataCacheService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiDataCacheServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiDataProvider.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintVelocityServiceImpl.java, customapi/src/main/resources/application.properties, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiDataProviderTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/KpiHelperServiceTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiDataCacheServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintVelocityServiceImplTest.java
Change log: KPI level Cache changes
=> DTS-42419: Sprint Velocity KPI Cache implementation

UI/src/app/config/dashboard-config/dashboard-config.component.ts
Reverts PublicisSapient/PSknowHOW#1918
=> Revert "DTS-43768: all option added for SUPERADMIN"

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/RepoToolMeanTimeToMergeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpiintegration/service/KpiIntegrationServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIExcelData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/MergeRequests.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/repotools/model/RepoToolValidationData.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KPIExcelUtility.java
https://publicissapient.atlassian.net/browse/DTS-44062
=> Dts 44062 slingshot integration imple kk

customapi/src/main/java/com/publicissapient/kpidashboard/apis/filter/service/FilterHelperService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java
Change-log: OOM issue investigation
=> DTS-44232: Disable new cache of projects

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java, processors/github-action/src/main/java/com/publicissapient/kpidashboard/githubaction/processor/GitHubActionProcessorJobExecutor.java, processors/github-action/src/main/java/com/publicissapient/kpidashboard/githubaction/processor/adapter/impl/GitHubActionBuildClient.java, processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/service/JiraCommonServiceTest.java
https://publicissapient.atlassian.net/browse/DTS-44109
=> DTS-44109: build frequency build name fix-kk

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/BitBucketServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpiintegration/service/KpiIntegrationServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/BitBucketServiceRTest.java
https://publicissapient.atlassian.net/browse/DTS-44355
=> DTS-44355: kpi-integration api fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintGoalServiceImpl.java
Change-log:Sprint goals sorted on start date.
https://publicissapient.atlassian.net/browse/DTS-44372
=> DTS-44372: Sprint Goals sorted

customapi/src/main/java/com/publicissapient/kpidashboard/apis/bitbucket/service/BitBucketServiceR.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/bitbucket/service/BitBucketServiceRTest.java
https://publicissapient.atlassian.net/browse/DTS-44411
=> DTS-44411: branch and developer filter reset fix

database-scripts/installation-script/organization hierarchy installation script.js
https://publicissapient.atlassian.net/browse/DTS-44389
installation script to insert entries in organization_hierarchy collection by maintaining parent-child relationship
=> organization_hierarchy installation script

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java
Change log: log injection issue fix
=> Bug fix/DTS 43967 empty project name check

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1300/ChangeKpiMasterDocumentationLink.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1300/ChangeKpiMasterDocumentationLink.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
https://publicissapient.atlassian.net/browse/DTS-44507
=> DTS-44507: update kpi document url

customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/model/HierarchyResponseDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/service/ProjectBasicConfigServiceImpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/ProjectBasicConfigServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-44666
=> DTS-44666: semaphore compatibility fix for hierarchy changes

UI/src/app/dashboardv2/filter-v2/parent-filter/parent-filter.component.ts, UI/src/app/dashboardv2/filter-v2/primary-filter/primary-filter.component.ts, UI/src/app/dashboardv2/kpi-card-v2/kpi-card-v2.component.ts
Remove console logs and localstorage.setitem of selectedTrend from primary filter & parent filter
=> DTS-44370: issue fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/abac/ProjectAccessManager.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/abac/ProjectAccessManagerTest.java
… while raising the request for the projects.
Change log: Defect Fix for Projects accesses are overriding for non-super admin users while raising the request for the projects.
=> Bug fix/DTS-44614 project access

customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeQualityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeViolationsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarTechDebtServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/UnitCoverageServiceimpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeQualityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarTechDebtServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarViolationsServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/UnitCoverageServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-45171: all sonar kpis
=> DTS-45171: align sprint date logic change

common/src/main/java/com/publicissapient/kpidashboard/common/feature/FeatureEnum.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/jobs/RallyProcessorJob.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/listener/JobStepProgressListener.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/model/Release.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/model/ReleaseWrapper.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/model/WorkProducts.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/processor/RallyIssueProcessorImpl.java, processors/rally/src/main/java/com/publicissapient/kpidashboard/rally/service/FetchScrumReleaseDataImpl.java
Change log: Release Tab Changes
=> DTS-44509: Release Tab Filter Enhancement for rally

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/CodeBuildTimeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jenkins/service/JenkinsServiceR.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/SprintDetailsService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/SprintDetailsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeQualityServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeViolationsServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarKPIService.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarTechDebtServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/sonar/service/UnitCoverageServiceimpl.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jenkins/service/BuildFrequencyServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/jenkins/service/CodeBuildTimeServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/CodeQualityServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarTechDebtServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/SonarViolationsServiceImplTest.java, customapi/src/test/java/com/publicissapient/kpidashboard/apis/sonar/service/UnitCoverageServiceImplTest.java
https://publicissapient.atlassian.net/browse/DTS-45171
=> Dts 45171 align sprint dates kk

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/CycleTimeServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1310/DefectRejectionRateFieldMappingUpdate.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1310/DefectRejectionRateFieldMappingUpdate.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
https://publicissapient.atlassian.net/browse/DTS-45931
=> DTS-45931: DRR remove mandatory from Status to identify rejected defects

common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMappingHistory.java, common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/enums/FieldMappingEnum.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IterationCommitmentServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1100/ItrCommitmentChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1100/ItrCommitmentChangeUnit.java, customapi/src/main/resources/json/mongock/default/field_mapping_structure.json
Change-log: Added scope change based on label in ITR commitment KPI
=> DTS-45927: ITR commit gs enhc

customapi/src/test/resources/json/default/scrum_project_field_mappings.json
Change-log: Added scope change based on label in ITR commitment KPI
=> DTS-45927: ITR commit gs enhc test case

UI/package.json, UI/src/app/dashboardv2/reports-module/report-container/report-container.component.ts
=> Report UI issue fix : preetier fix

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IterationCommitmentServiceImpl.java
Change-log: GS enhc ITR commitment KPI's
=> DTS-45927: GS ITR commitment enhc.

customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1100/ChangeKpiMasterDocumentationLink.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
https://publicissapient.atlassian.net/browse/DTS-46192
=> DTS-46192: change kpi doc url

customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/LateRefinementServiceImpl.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/rollback/release_1100/LateRefinementChangeUnit.java, customapi/src/main/java/com/publicissapient/kpidashboard/apis/mongock/upgrade/release_1100/LateRefinementChangeUnit.java, customapi/src/main/resources/json/mongock/default/kpi_master.json
Change log: KPI Renaming and Link update
=> DTS-46744: GS_LateRefinement_Change
