PublicisSapient/PSknowHOW

- .gitignore
> sync with master

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/abac/ProjectAccessManager.java
any user raise request role with Superadmin and any hierarchy or project level then denied request from api
> Denied request of role with Super Admin and any Level of access

- UI/src/app/dashboard/executive/executive.component.html
- UI/src/app/dashboard/executive/executive.component.spec.ts
- UI/src/app/dashboard/executive/executive.component.ts
- UI/src/app/services/excel.service.ts
Reverts PublicisSapient/PSknowHOW#83
> Revert "DTS-19060 column ordering for excel"

- UI/src/app/services/excel.service.ts
Reverts PublicisSapient/PSknowHOW#82
> Revert "DTS-19060 added check for when url is not available"

- common/src/main/java/com/publicissapient/kpidashboard/common/constant/CommonConstant.java
- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/KPIFieldMapping.java
- common/src/main/java/com/publicissapient/kpidashboard/common/repository/application/KpiFieldMappingRepository.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/appsetting/service/ConfigHelperService.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/KpiHelperService.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpis/KPIFieldMappingController.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/model/KPIFieldMappingResponse.java
- mongodb/scripts/kpi_fieldmapping_insert.js
Adding new API KPIFieldMapping.
> Adding new get API KPIFieldMapping.

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/common/service/impl/UserInfoServiceImpl.java
Creating project access for ldap Superadmin.
> Creating project access for ldap Superadmin.

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/service/FieldMappingServiceImplTest.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageKanbanServiceImplTest.java
- processors/azure/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImplTest.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/metadata/MetaDataClientImpl.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/offline/OfflineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/KanbanJiraIssueClientImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/OnlineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/ScrumJiraIssueClientImplTest.java
Removing Redundant or unused fields.
> Removing Redundant or unused fields from FieldMapping

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
> reverting back few changes in fieldmapping.

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
Reverts PublicisSapient/PSknowHOW#148
> Revert "reverting back few changes in fieldmapping."

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/service/FieldMappingServiceImplTest.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageKanbanServiceImplTest.java
- processors/azure/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImplTest.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/metadata/MetaDataClientImpl.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/offline/OfflineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/KanbanJiraIssueClientImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/OnlineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/ScrumJiraIssueClientImplTest.java
Reverts PublicisSapient/PSknowHOW#143
> Revert "Removing Redundant or unused fields from FieldMapping"

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/fieldmapping/service/FieldMappingServiceImpl.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/service/FieldMappingServiceImplTest.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageKanbanServiceImplTest.java
- processors/azure/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImplTest.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/metadata/MetaDataClientImpl.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/offline/OfflineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/KanbanJiraIssueClientImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/OnlineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/ScrumJiraIssueClientImplTest.java
Removing Unused fields from fieldmapping
> Removing Unused fields from fieldmapping

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/FieldMapping.java
- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/FieldMappingDTO.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/fieldmapping/service/FieldMappingServiceImpl.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/service/service/FieldMappingServiceImplTest.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/zephyr/service/RegressionPercentageKanbanServiceImplTest.java
- processors/azure/azure-boards/src/main/java/com/publicissapient/kpidashboard/azure/client/metadata/MetaDataClientImpl.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/KanbanAzureIssueClientImplTest.java
- processors/azure/azure-boards/src/test/java/com/publicissapient/kpidashboard/azure/client/azureissue/ScrumAzureIssueClientImplTest.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/metadata/MetaDataClientImpl.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/offline/OfflineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/KanbanJiraIssueClientImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/OnlineDataProcessorImplTest.java
- processors/jira/src/test/java/com/publicissapient/kpidashboard/jira/processor/mode/impl/online/ScrumJiraIssueClientImplTest.java
Reverts PublicisSapient/PSknowHOW#155
> Revert "Removing Unused fields from fieldmapping"

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintPredictabilityImpl.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DSRServiceImplTest.java
- customapi/src/test/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/SprintPredictabilityImplTest.java
fix for aggregation tree for sprint predictability
> Gs enhancements to master 

- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/KPIFieldMapping.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/kpis/KPIFieldMappingController.java
- mongodb/scripts/kpi_fieldmapping_insert.js
Adding kpifield mapping script and controller.
> Adding kpifield mapping script and controller.

- mongodb/scripts/mongodb_start.sh
adding kpi_fieldmapping script in mongodb.start.sh
> Adding kpifield mapping script in mongodb_start.sh file

- mongodb/scripts/kpi_fieldmapping_insert.js
adding missing fields in kpi_fieldmapping script.
> Adding missing field in kpi_fieldmapping script

- processors/sonar/src/main/java/com/publicissapient/kpidashboard/sonar/processor/adapter/impl/Sonar8Client.java
- processors/sonar/src/test/java/com/publicissapient/kpidashboard/sonar/processor/Sonar8ClientTest.java
Reverts PublicisSapient/PSknowHOW#251
> DTS-20333 - Revert "removed timezone fix of sonar"

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/sprint/SprintClientImpl.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/util/JiraProcessorUtil.java
Impact of code :
Timezone is Changes to UTC , Iteration board Sprint Date And other Dashboard KPIs
> DTS-20532 - Sprint start date format changes as per ISO TimeZone (UTC format)  

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraToolConfigServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/service/JiraToolCredentialProviderForCustomApi.java
added jira credentials proder for fetching board data
> added vault interface support

- common/pom.xml
- customapi/pom.xml
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ClosurePossibleTodayServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DailyClosureServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimateVsActualServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimationHygieneServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IssueLikelyToSpillServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ScopeChangeServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkCompletedServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkRemainingServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java
- notification-consumer/pom.xml
- pom.xml
- processors/azure/azure-boards/pom.xml
- processors/azurepipeline/pom.xml
- processors/azurerepo/pom.xml
- processors/bamboo/pom.xml
- processors/bitbucket/pom.xml
- processors/github/pom.xml
- processors/gitlab/pom.xml
- processors/jenkins/pom.xml
- processors/jira/pom.xml
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/adapter/impl/OnlineAdapter.java
- processors/jiratest/pom.xml
- processors/sonar/pom.xml
- processors/teamcity/pom.xml
- processors/zephyr/pom.xml
Iteration kpi changes from sprint report and epic fetch issue fix
> Hotfix Release 6.0.3

- common/pom.xml
- customapi/pom.xml
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ClosurePossibleTodayServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/DailyClosureServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimateVsActualServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/EstimationHygieneServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/IssueLikelyToSpillServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/ScopeChangeServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkCompletedServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/WorkRemainingServiceImpl.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/util/KpiDataHelper.java
- notification-consumer/pom.xml
- pom.xml
- processors/azure/azure-boards/pom.xml
- processors/azurepipeline/pom.xml
- processors/azurerepo/pom.xml
- processors/bamboo/pom.xml
- processors/bitbucket/pom.xml
- processors/github/pom.xml
- processors/gitlab/pom.xml
- processors/jenkins/pom.xml
- processors/jira/pom.xml
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/adapter/impl/OnlineAdapter.java
- processors/jiratest/pom.xml
- processors/sonar/pom.xml
- processors/teamcity/pom.xml
- processors/zephyr/pom.xml
Reverts PublicisSapient/PSknowHOW#324
> Hotfix Release 6.0.3 

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/ScrumJiraIssueClientImpl.java
Reverts PublicisSapient/PSknowHOW#361
we do not merge any changes of gs in develop branch
> Revert "Subtask addition in Quality KPI for GS"

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/ScrumJiraIssueClientImpl.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/util/JiraConstants.java
This change is merged in GS master branch but not in ps knowHOW develop branch as of now
> DTS-21330 (Final Subtask change for GS)

- UI/src/app/config/project-config/basic-config/basic-config.component.html
- UI/src/app/config/project-config/basic-config/basic-config.component.spec.ts
- UI/src/app/config/project-config/basic-config/basic-config.component.ts
- UI/src/app/config/project-config/project-list/project-list.component.ts
- UI/src/app/config/project-config/tool-menu/tool-menu.component.css
- UI/src/app/config/project-config/tool-menu/tool-menu.component.html
- UI/src/app/config/project-config/tool-menu/tool-menu.component.spec.ts
- UI/src/app/config/project-config/tool-menu/tool-menu.component.ts
- UI/src/app/services/http.service.ts
- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/ProjectBasicConfig.java
- common/src/main/java/com/publicissapient/kpidashboard/common/model/application/dto/ProjectBasicConfigDTO.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/basic/rest/ProjectBasicConfigController.java
- customapi/src/main/java/com/publicissapient/kpidashboard/apis/projectconfig/projecttoolconfig/service/ProjectToolConfigServiceImpl.java
Reverts PublicisSapient/PSknowHOW#399
> Revert "DTS_21575 add toggle"

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/ScrumJiraIssueClientImpl.java
This Changes Do not merge in Master branch. beacuse of we had separate flow of zephyr squad as Jira Test tool on master/develop branch , but GS master is based on old flow
> GS | DTS-21864 - In-spint KPI issue fix (Jira-zephyr Squad changes)

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/jira/scrum/service/RCAServiceImpl.java
> DTS-22291: Removed Sunbelt Rentals Null Exception.

- customapi/src/main/java/com/publicissapient/kpidashboard/apis/config/WebSecurityConfig.java
deleted previously by mistake by eswar , https://github.com/PublicisSapient/PSknowHOW/commit/57c795d44026184cdd1e11a263bab96c048091fa
> revert file WebSecurityConfig , 

- UI/src/app/config/project-config/field-mapping/field-mapping.component.html
- mongodb/scripts/kpi_master_insert.js
DTS-22062 -Lead time KPI enhancement
> DTS-22062 -Lead time KPI enhancement

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/ScrumJiraIssueClientImpl.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/util/JiraConstants.java
Subtask defect changes to be merged in PS knowHow
> DTS_22439 - subtask defect code 

- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/KanbanJiraIssueClientImpl.java
- processors/jira/src/main/java/com/publicissapient/kpidashboard/jira/client/jiraissue/ScrumJiraIssueClientImpl.java
Handle null pointer exception when jira processor failed
> Dts 22167 save assignee jira
